@TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IjIyMTFAbWFpbC5jb20iLCJzdWIiOjEsIm5hbWUiOiJsdWNhcyIsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE3MjQ4NjMxMDIsImV4cCI6MTcyNzQ1NTEwMn0.uGWgiuciW7mGWGEXQfHFvLmM-arSAxtNjrLUUdGoPLk
@BASEURL=http://localhost:3000
### Login
POST {{BASEURL}}/login
Content-Type: application/json

{
  "email": "admin@mail.com",
  "password": "1234"
}
### Create New User
POST {{BASEURL}}/users
Content-Type: application/json

{
  "email": "admin@mail.com",
  "password": "1234",
  "name": "lucas",
}

### Get All Users
GET {{BASEURL}}/users

### Update an User
PATCH {{BASEURL}}/users/1
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
  "id": 1,
  "email": "admin@mail.com",
  "name": "lucas 2",
  "isAdmin": true
}

### Delete an User
DELETE {{BASEURL}}/users/10

###  =========== TRAITS ========== 

### Get All Traits
GET {{BASEURL}}/users/traits
Content-Type: application/json

### Get Specific Trait
GET {{BASEURL}}/users/traits/1
Content-Type: application/json

### Create a Trait
POST {{BASEURL}}/users/1/traits
Content-Type: application/json

{
  "name": "Funny"
}

### Update a Trait
PATCH {{BASEURL}}/users/traits/1
Content-Type: application/json

{
  "name": "Cool"
}

### Delete a Trait
DELETE {{BASEURL}}/users/traits/1
Content-Type: application/json
